### ISSUE TITLE
Trouble with cstats during installation

### ISSUE THREAD

**Issue by Lucas97223** [lindermanlab/ssm#169]
Hi, 
I am trying to install the ssm package on my windows 11, python 3.10.14. The installation succeeded but when I try to import(ssm) i get:
>>> import ssm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\ssm\ssm\__init__.py", line 3, in <module>
    from .hmm import *
  File "C:\Users\...\ssm\ssm\hmm.py", line 8, in <module>
    from ssm.optimizers import adam_step, rmsprop_step, sgd_step, convex_combination
  File "C:\Users\...\ssm\ssm\optimizers.py", line 17, in <module>
    from ssm.primitives import solve_symm_block_tridiag
  File "C:\Users\...\ssm\ssm\primitives.py", line 10, in <module>
    from ssm.cstats import _blocks_to_bands_lower, _blocks_to_bands_upper, \
ModuleNotFoundError: No module named 'ssm.cstats'

I tried to do this install on two different machines but i got the same problem. How should this be solved?
Thanks!

**Comment by researcherofreality** [comment]
Hi Lucas, have you tried running "pip install -e ." in the /ssm directory? It should install the necessary ssm.cstats from setup.py
